version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - run:
          command: java -jar BuildTools.jar --rev 1.14.3

      - store_artifacts:
          path: spigot-1.14.3.jar
